'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class EconsaveDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=EconsaveDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Items() As DbSet(Of Item)
    Public Overridable Property ItemSales() As DbSet(Of ItemSale)
    Public Overridable Property Staffs() As DbSet(Of Staff)
    Public Overridable Property Transactions() As DbSet(Of Transaction)

End Class
