'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Item
    Public Property itemID As String
    Public Property name As String
    Public Property description As String
    Public Property price As Double
    Public Property stockQuantity As Integer
    Public Property createdOn As Date
    Public Property lastUpdate As Nullable(Of Date)
    Public Property category As String
    Public Property status As Integer

    Public Overridable Property ItemSales As ICollection(Of ItemSale) = New HashSet(Of ItemSale)

End Class
