'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sales
    Public Property staffID As String
    Public Property name As String
    Public Property password As String
    Public Property registeredOn As Date
    Public Property lastLogin As Nullable(Of Date)
    Public Property position As Integer

    Public Overridable Property Transactions As ICollection(Of Transaction) = New HashSet(Of Transaction)

End Class
