'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transaction
    Public Property transactionID As String
    Public Property staffID As String
    Public Property totalPrice As Double
    Public Property createdOn As Date

    Public Overridable Property ItemSale As ItemSale
    Public Overridable Property Staff As Sales

End Class
